---

# These are the global parameters that provide defaults for all the
# provisioning templates that we import. Override the default parameters in the hostgroups

# Tell the YAML linter to ignore long lines
# yamllint disable rule:line-length

global_parameters:
  - name: "ansible_controller_api_url"
    value: "https://aapcontroller24.savage.test/api/v2"
    parameter_type: "string"
    hidden_value: false
    state: "present"

  - name: "ansible_host_config_key"
    value: "{{ satellite_ansible_callback_config_key_vault }}"
    parameter_type: "string"
    hidden_value: false
    state: "present"

  - name: "ansible_job_template_id"
    value: 13
    parameter_type: "integer"
    hidden_value: false
    state: "present"

  - name: "ansible_roles_check_mode"
    value: false
    parameter_type: "boolean"
    hidden_value: false
    state: "present"

  - name: "ansible_tower_provisioning"
    value: false
    parameter_type: "boolean"
    hidden_value: false
    state: "present"

  - name: "enable-epel"
    value: false
    parameter_type: "boolean"

  - name: "enable-remote-execution-pull"
    value: false
    parameter_type: "boolean"

  - name: "fips_enabled"
    value: false
    parameter_type: "boolean"

  - name: "encrypt_grub"
    value: false
    parameter_type: "boolean"

  - name: "grubmenu_pass"
    value: "grub.pbkdf2.sha512.10000.C33394FC6B000C350BEDDA8E83540C4B2AC153581D9BEFA537E6C0015D7277F6014AED40961E8A16C2C3E9639ABE65D0BD7663D6FCD0A85695953D93A1F35F31.F0DBD97E1C4F981516D2BA19C9534C6A8DD2804B71CDCF8264948D1C19A8AC6A9D3E03DEAEA6AD596C811F6A94359967F09C078290EF2E685C0DB2175411C02F"
    parameter_type: "string"
    hidden_value: true

  - name: "host_packages"
    value: "vim"
    parameter_type: "string"

  - name: "host_registration_insights"
    value: true
    parameter_type: "boolean"

  - name: "host_registration_remote_execution"
    value: true
    parameter_type: "boolean"

  - name: "install_environment_group"
    value: "server-product-environment"
    parameter_type: "string"

  - name: "install_reboot_kexec"
    value: false
    parameter_type: "boolean"

  - name: "network_zone"
    value: "public"
    parameter_type: "string"

  - name: "package_upgrade"
    value: true
    parameter_type: "boolean"

  - name: "redhat_install_agent"
    value: false
    parameter_type: "boolean"

  - name: "redhat_install_host_tools"
    value: true
    parameter_type: "boolean"

  - name: "redhat_install_host_tracer_tools"
    value: true
    parameter_type: "boolean"

  - name: "remote_execution_create_user"
    value: true
    parameter_type: "boolean"

  - name: "remote_execution_effective_user_method"
    value: "sudo"
    parameter_type: "string"

  - name: "remote_execution_ssh_keys"
    value: "{{ remote_execution_ssh_keys_vault }}"
    parameter_type: "string"

  - name: "remote_execution_ssh_user"
    value: "{{ remote_execution_ssh_user_vault }}"
    parameter_type: "string"

  - name: "remove_default_passphrase"
    value: true
    parameter_type: "boolean"

  - name: "use_foreman_users"
    value: true
    parameter_type: "boolean"

  - name: "use_graphical_installer"
    value: false
    parameter_type: "boolean"

  - name: "use_ntp"
    value: false
    parameter_type: "boolean"
