---
satellite_subnets:
  - name: "savage.test"
    description: "savage.test network"
    network_type: "IPv4"
    network: 172.16.0.0
    prefix: 23
    mask: 255.255.254.0
    gateway: 172.16.0.1
    dns_primary: 172.16.0.11
    dns_secondary: 8.8.8.8
    ipam: "Internal DB"
    from_ip: 172.16.0.100
    to_ip: 172.16.0.199
    boot_mode: "Static"
    discovery_capsule: "{{ satellite_fqdn }}"
    tftp_capsule: "{{ satellite_fqdn }}"
    dns_capsule: "{{ satellite_fqdn }}"
    template_capsule: "{{ satellite_fqdn }}"
    parameters:
      - name: "Parameter1"
        parameter_type: string
        value: "theParameter"
    remote_execution_capsules:
      - "{{ satellite_fqdn }}"
    domains:
      - "{{ satellite_domain }}"
    locations:
      - "{{ satellite_location }}"
    organizations:
      - "{{ satellite_organization }}"

  - name: "bond_subnet"
    description: "savage.test bond network"
    network_type: "IPv4"
    network: 172.16.2.0
    prefix: 23
    mask: 255.255.254.0
    gateway: 172.16.2.1
    dns_primary: 172.16.0.5
    dns_secondary: 8.8.8.8
    ipam: "None"
    boot_mode: "Static"
    dns_capsule: "{{ satellite_fqdn }}"
    domains:
      - "{{ satellite_domain }}"
    locations:
      - "{{ satellite_location }}"
    organizations:
      - "{{ satellite_organization }}"
