---

# Set these if you are forwarding zones (you probably are not)
# idm_dns_forward_zones:
#   - name: "savage.test"
#     forwarders:
#       - ip_address: "192.168.252.5"
#       - ip_address: "192.168.252.6"
#     forward_policy: "only"
#     skip_overlap_check: true

# Set the bind policy for zones managed by the IdM server
# The realm-capsule bind policy should be much more restrictive
idm_dns_update_zones:
  - name: "savage.test"
    foreman_proxy_BIND_update_policy: 'grant SAVAGE.TEST krb5-self * A; grant SAVAGE.TEST krb5-self * AAAA; grant SAVAGE.TEST krb5-self * SSHFP; grant realm-capsule\@SAVAGE.TEST wildcard * ANY;' # noqa yaml[line-length]
  - name: "16.172.in-addr.arpa"
    foreman_proxy_BIND_update_policy: 'grant SAVAGE.TEST krb5-subdomain 16.172.in-addr.arpa. PTR; grant realm-capsule\@SAVAGE.TEST wildcard * ANY;'
  - name: "0.16.172.in-addr.arpa"
    foreman_proxy_BIND_update_policy: 'grant SAVAGE.TEST krb5-subdomain 0.16.172.in-addr.arpa. PTR; grant realm-capsule\@SAVAGE.TEST wildcard * ANY;'

# you probably want to add some standard records to the new DNS
idm_dns_records:
  - name: "nas3"
    zone_name: "savage.test"
    record_type: "A"
    ip_address: "172.16.0.99"
    a_create_reverse: true
    state: "present"

  - name: "hpswitch"
    zone_name: "savage.test"
    record_type: "A"
    ip_address: "172.16.0.2"
    state: "present"

  - name: "vcenter"
    zone_name: "savage.test"
    record_type: "A"
    ip_address: "172.16.0.90"
    a_create_reverse: true
    state: "present"

  - name: "c3esx1"
    zone_name: "savage.test"
    record_type: "A"
    ip_address: "172.16.0.91"
    a_create_reverse: true
    state: "present"

  - name: "c3esx2"
    zone_name: "savage.test"
    record_type: "A"
    ip_address: "172.16.0.92"
    a_create_reverse: true
    state: "present"

  - name: "c3esx3"
    zone_name: "savage.test"
    record_type: "A"
    ip_address: "172.16.0.93"
    a_create_reverse: true
    state: "present"

  - name: "c3esx4"
    zone_name: "savage.test"
    record_type: "A"
    ip_address: "172.16.0.94"
    a_create_reverse: true
    state: "present"

  - name: "c3esx5"
    zone_name: "savage.test"
    record_type: "A"
    ip_address: "172.16.0.95"
    a_create_reverse: true
    state: "present"

  - name: "c3esx6"
    zone_name: "savage.test"
    record_type: "A"
    ip_address: "172.16.0.96"
    a_create_reverse: true
    state: "present"

  - name: "c3esx7"
    zone_name: "savage.test"
    record_type: "A"
    ip_address: "172.16.0.97"
    a_create_reverse: true
    state: "present"
